# Generated by Django 4.1.7 on 2023-03-16 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumbPodcast')),
                ('description', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('TERROR', 'Terror'), ('COMEDIA', 'Comédia'), ('SUSPENSE', 'Suspense'), ('HUMOR', 'Humor'), ('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('DRAMA', 'Drama'), ('INFANTIL', 'Infantil')], max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
